[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
cargo-dist-version = "0.31.0"
ci = "github"
installers = ["homebrew"]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
hosting = "github"

[dist.homebrew]
# Setting tap to the same repo so permissions just work
tap = "Yahddyyp/rudo"
formula = "rudo"
