[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
cargo-dist-version = "0.31.0"
ci = "github"
installers = ["homebrew"]
# Standard targets that work on all GitHub accounts
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
hosting = "github"

[dist.homebrew]
tap = "Yahddyyp/homebrew-rudo"
formula = "rudo"
